// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const wrapper: string;
export const pagetitle: string;
export const info_wrapper: string;
export const title: string;
export const content_wrapper: string;
export const image_wrapper: string;
export const image: string;
export const text_wrapper: string;
export const box: string;
export const icon: string;
export const text: string;
export const post: string;
export const gallery: string;
export const navi: string;
export const nocard: string;
export const card: string;
